version: "3.9"

services:
  top-langs:
    image: ferasaljoudi/top-langs:latest
    platform: linux/arm64
    ports:
      - "85:80"
    environment:
      - GITHUB_TOKEN=*********************************
    deploy:
      resources:
        limits:
          memory: 256M
    restart: unless-stopped
