version: '3.9'

services:
  top-langs:
    platform: linux/arm64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "86:86"
    environment:
      - GITHUB_TOKEN=*************************************
